# Generated by Django 5.2.6 on 2025-10-28 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("zingmind", "0004_assets_attendance_departments_employeeappraisals_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="employees",
            options={},
        ),
    ]
